app/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()
admin.site.enable_nav_sidebar = False


urlpatterns = [
    path('', include('device.urls', namespace='device')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'switch admin'
admin.site.site_title = 'switch admin'
admin.site.site_url = 'http://localhost:8000/'
admin.site.index_title = 'switch administration'

app/device/urls.py
from django.urls import path
from . import views

app_name = 'device'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('devices', views.deviceListView, name = 'list'),
    path('devices-test', views.deviceTestView, name = 'test'),
    path('detail/<int:id>/', views.deviceDetailView, name='detail'),
]

app/device/models.py
from django.db import models
from django.urls import reverse

class Department(models.Model):

    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name



class Device(models.Model):

    name = models.CharField(max_length=500)
    department = models.ForeignKey(Department, related_name='devices', on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('device:detail',args=[self.id])

app/device/views.py
from django.shortcuts import render, get_object_or_404
from .models import Device
import platform    # For getting the operating system name
import subprocess  # For executing a shell command

def ping(host):
    """
    Returns True if host (str) responds to a ping request.
    Remember that a host may not respond to a ping (ICMP) request even if the host name is valid.
    """

    # Option for the number of packets as a function of
    param = '-n' if platform.system().lower()=='windows' else '-c'

    # Building the command. Ex: "ping -c 1 google.com"
    command = ['ping', param, '1', host]

    return subprocess.call(command) == 0

def home(request):
    return render(request, 'home.html')

def deviceListView(request):
    devices = Device.objects.all()
    context = {
        'object_list': devices,
        }
    return render(request, 'device/device-list.html', context)

def deviceDetailView(request, id):
    device = get_object_or_404(Device, id = id)
    context = {
        'object': device,
        }
    return render(request, 'device/device-detail.html', context)

def deviceTestView(request):

    devices = Device.objects.all()
    for device in devices:
        device_ping = ping(device.name)
        device.status = device_ping

    Device.objects.bulk_update(devices, ['status'])
    # google.com
    # github.com
    # office.com
    # linkedin.com


    context = {
        'object': 'test',
        }
    return render(request, 'device/device-test.html', context)

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}{% endblock %}
    <link rel="shortcut icon" type="image/ico" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/message.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<style>

</style>
<body id="main_body" class="">

{% include 'messages.html' %}
{% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

<script src="{% static 'js/jquery-3.5.1.slim.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script type="application/javascript">
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
    $(document).ready(function(){
        $('#exampleModal').modal({show:true});
    });

const td_targets = document.getElementsByClassName("td-targets")
  for (let index = 0; index < td_targets.length; index++) {
    const element = td_targets[index];
      element.addEventListener("click", function() {
        var tarhref = this.dataset.tarhref
        location.href=tarhref;
      });
  }
</script>
<style>
    .navbar {
        border-bottom: 2px solid rgb(30, 30, 30);
    }
    .navbar-nav {
        display: inline-block;
    }

    .navbar-nav>li {
        display: inline-block;
    }
    
    .avatar {
        width: 5rem;
        height: 5rem;
        border-radius: 50%;
    }
    .avatar-small {
        width: 2rem;
        height: 2rem;
        border-radius: 50%;
    }
    </style>
</body>
</html>

app/templates/device/device-detail.html
{% extends 'base.html' %}


{% block title %}<title>{{ object.name }}</title>{% endblock %}



{% block content %}
<div class="container-fluid mt-5">
  <div class="row no-gutters">


    <div class="col-md-2 d-none d-sm-block">
      
    </div>


    <div class="col-md-8 col-sm-12">
      <div class="">
        <h1>{{ object.name }}</h1>
        
        <p>{{ object.status }}</p>
      </div>
      <a href="{% url 'device:list' %}">back to list of devices</a>
    </div>
    <div class="col-md-2 d-none d-sm-block">
    </div>
  </div>
  
  
</div>



{% endblock %}

app/templates/device/device-list.html
{% extends 'base.html' %}

{% block title %}<title>List of Devices</title>{% endblock %}

{% block content %}

<div class="container mt-5 ">
  <div class="row">
    <div class="col-1">
      {% for object in object_list %}
        <p class="">
          <a href="{{ object.get_absolute_url }}">
            {{ object.name }}
          </a>
        </p>
      {% endfor %}
    </div>
    <div class="col-1">
      <br>
    </div>
    <div class="col-10">
      <div class="row">
        {% for object in object_list %}
        <div class="col">
          <p class="p-5 btn {% if object.status %} btn-outline-success {% else %} btn-outline-danger {% endif %}">
            <a href="{{ object.get_absolute_url }}">
              {{ object.name }}
            </a>
          </p>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div>


{% endblock %}

app/templates/device/device-test.html
{% extends 'base.html' %}


{% block title %}<title>Test</title>{% endblock %}



{% block content %}
<div class="container-fluid mt-5">
  <div class="row no-gutters">


    <div class="col-md-2 d-none d-sm-block">
      
    </div>


    <div class="col-md-8 col-sm-12">
      <div class="">
        <h1>test </h1>
        <p>{{ object }}</p>
        
      </div>
    </div>
    <div class="col-md-2 d-none d-sm-block">
    </div>
  </div>
  
  
</div>



{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>a code | coding with python</title>{% endblock %}

{% block content %}

  <div class="container mt-5">
    <div class="row">
      <div class="col mb-3">
        <div class="card border-primary bg-dark text-center">
          <div class="card-body text-primary">
            <h5 class="card-title">Learn to Code</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-12 mb-3">
        <div class="card border-primary bg-dark">
          <div class="card-body text-primary">
            <h5 class="card-title">Python</h5>
            <p class="card-text">Coding</p>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card border-primary bg-dark">
          <div class="card-body text-primary">
            <h5 class="card-title">Django</h5>
            <p class="card-text">Web development</p>
          </div>
        </div>
      </div>
    </div> <!-- row -->
      
  </div> <!-- container main -->


</div>
{% endblock %}

app/templates/messages.html
{% if messages %}

{% for message in messages %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog h-100 d-flex flex-column justify-content-center my-0" role="document">

    <div class="modal-content {{ message.tags }}">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{ message }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    <!-- modal-content -->

  </div>
</div>
<!-- Modal -->
{% endfor %}
{% endif %}

app/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="navbar-brand ml-4" href="#"><img src="{% static 'img/A.jpg' %}" alt="logo" width="30%" height="30%"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'device:list' %}">Devices</a>
      </li> 
      <li class="nav-item">
        <a class="nav-link" href="{% url 'device:test' %}">Test</a>
      </li> 
      
    </ul>

    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="#ffffff" d="M272 304h-96C78.8 304 0 382.8 0 480c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32C448 382.8 369.2 304 272 304zM48.99 464C56.89 400.9 110.8 352 176 352h96c65.16 0 119.1 48.95 127 112H48.99zM224 256c70.69 0 128-57.31 128-128c0-70.69-57.31-128-128-128S96 57.31 96 128C96 198.7 153.3 256 224 256zM224 48c44.11 0 80 35.89 80 80c0 44.11-35.89 80-80 80S144 172.1 144 128C144 83.89 179.9 48 224 48z"/></svg>
   
    
  </div>   <!-- collapse end -->
</nav>

app/templates/staff/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-9 mb-4">
                <div class="block-4-text p-4">
                    <h3>Username: {{ object }}</h3>
                    <a class="btn btn-success" href="{% url 'account_reset_password' %}">Reset password</a>
                    <hr>
                    {% if object.image %}
                        <img src="{{ object.image.url }}" alt="avatar" width="100" height="100">
                    {% else %}
                        <div ><svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 448 512"><path d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0S96 57.3 96 128s57.3 128 128 128zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
                    {% endif %}
                    <hr>
                    <a class="btn btn-success" href="{% url 'accounts:profile-update' %}">Change your photo</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/staff/profile_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-9 mb-4">
                <div class="block-4-text p-4">
                    <h3>update photo</h3>
                    <hr>
                    <form method="post" enctype="multipart/form-data" class="form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Upload</button>
                    </form>
                    <hr>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}